### ISSUE TITLE
Unable to add new Sellfino Helpdesk section on Prestige theme

### ISSUE THREAD

**Issue by tribecollective** [sellfino/Helpdesk-FAQ#1]
[
<img width="552" alt="Screenshot 2021-08-16 at 4 54 49 PM" src="https://user-images.githubusercontent.com/89011334/129538382-32e8cb12-613d-4cb1-972f-f1a4da0724b5.png">
](url)

Hi, i am unable to add the new section as i receive this error message. "sections/sellfino.helpdesk.liquid" contains illegal characters

**Comment by sellfino** [comment]
@tribecollective It works without problem in Dawn theme. Try that and let me know if it works there.

Also, did you change the code of sellfino.helpdesk.liquid? If yes, please post the content of that file.

**Comment by tribecollective** [comment]
Hi

We are using prestige theme and have no plans to change the theme

Thanks anyway

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
